### ISSUE TITLE
Pointer to references on MS compiler

### ISSUE THREAD

**Issue by ebecz** [JeanLColombo/Pamola#15]
In this line I'm getting a error because of a pointer to a reference:

https://github.com/JeanLColombo/Pamola/blob/2b0904d5693514547e190c06bf19782ec32d8f1d/PamolaProject/PamolaProject/CircuitElement.h#L30

It can be seen on this question is it is quite frequently issue.
Does it work on MS compiler?

**Comment by JeanLColombo** [comment]
We've refactored the whole process of object handling by Pamola. This shouldn't be an issue when our hotfix is finished.
