### ISSUE TITLE
Local object passing to outside it's context.

### ISSUE THREAD

**Issue by ebecz** [JeanLColombo/Pamola#8]
On the line:

https://github.com/JeanLColombo/Pamola/blob/ca651d92bcadd9ba2b065520c09e9c929f28b282/PamolaProject/PamolaProject/CircuitTerminal.cpp#L39

We are creating a local object on the stack ```CircuitNode()```, then passing it's reference to ```CircuitTerminal::connectTo(CircuitNode &node)``` wich calls ```node.shared_from_this()```.

The question is: Does it it work? I'm not sure if shared_from_this handles stack allocation correctly.

**Comment by ebecz** [comment]
https://github.com/JeanLColombo/Pamola/pull/9

**Comment by JohniMichels** [comment]
We're still trying to make the ctor for a `CircuitElement` with working terminals, only after that we can see the problem on connect and disconnect
